spring.datasource.url=jdbc:postgresql://db:5432/${DB_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

pystats.api.url=http://fijstats:8000