INSERT INTO inspirational_quote (quote, source, tag) VALUES
('They put a hot wire to my head / Because of the things I did and said', '"Rise" - Public Image Ltd.', NULL),
('Anger is an energy.', '"Rise" - Public Image Ltd.', NULL),
('Virgil Cain is my name and I served on the Danville train.', '"The Night They Drove Old Dixie Down"-The Band', NULL),
('I love it when you call me Big Poppa', '"Big Poppa" - Notorious B.I.G.', NULL),
('Can I kick it? Yes you can.', '"Can I Kick It?" - A Tribe Called Quest', NULL),
('We are not monsters, we''re moral people / And yet we have the strength to do this.', '"Nemesis"-Shreikback', NULL),
('We are like Greeks. We are like Romans. / Centaurs and monkeys just cluster ''round us', '"Nemesis"-Shreikback', NULL),
('I''m gonna tell you how it''s gonna be.', '"Not Fade Away"-The Rolling Stones', NULL),
('Beware doll, you''re bound to fall', '"Like a Rolling Stone" - Bob Dylan', NULL),
('And Harry doesn''t mind if he doesn''t make the scene.', '"Sultans of Swing" - Dire Straits', NULL),
('I just keep on rolling along with the grace of the Lord above.', '"Heartbreaker" - Led Zepplin', NULL),
('Sometimes we''re not prepared for adversity.', '"Mercy, Mercy, Mercy" - The Cannonball Adderly Quartet', NULL),
('Funky Claude was running in and out / pulling kids out the ground', '"Smoke On the Water" - Deep Purple', NULL),
('They smelled of pubs and Wormwood Scrubs and too many right wing meetings.', '"Down in the Tube Station at Midnight" - The Jam', NULL),
('This dance ain''t for everybody. Only the sexy people.', '"Push It" - Salt-n-Pepa', NULL),
('Four young chiquitas in Omaha waitin'' for the band to return from the show.', '"We''re an American Band" - Grand Funk Railroad', 'neb-omaha'),
('The name is Big Daddy, yes big not little.', '"Ain''t No Half Steppin''" - Big Daddy Kane', NULL),
('Just tell me where it hurts and I''ll tell you who to call.', '"Quinn the Eskimo" - Bob Dylan', NULL),
('You just want to be on the side that''s winning.', '"Positively 4th Street" - Bob Dylan', NULL),
('Don''t you understand that''s not my problem?', '"Positively 4th Street" - Bob Dylan', NULL),
('All my failings exposed, gets a taste in my mouth as desperation takes hold', '"Love Will Tear Us Apart" - Joy Division', NULL),
('Tire tracks all across your back - I can see you''ve had your fun.', '"Crosstown Traffic"- Jimi Hendrix', NULL),
('Why don''t you get back into bed.', '"Reasons to be Cheerful, Part 3" - Ian Dury & the Blockheads', NULL),
('The juice of the carrot, the smile of the parrot / A little drop of claret - anything that rocks', '"Reasons to be Cheerful, Part 3" - Ian Dury & the Blockheads', NULL),
('He just grinned and shook my hand, "No" was all he said.', '"The Weight" - The Band', NULL),
('Then she opened up a book of poems and handed it to me, written by an Italian poet from the thirteenth century.', '"Tangled Up in Blue" - Bon Dylan', NULL),
('I know you''re dissatisfied with your position and your place.', '"Positively 4th Street" - Bob Dylan', NULL),
('I don''t know why I let that mean woman make me a fool.', '"Whipping Post" - The Allman Brothers', NULL),
('I had ''em all out there steppin'' and fetchin'' like their heads were on fire and their asses was catchin''.', '"The Ballad of Uneasy Rider" - Charlie Daniels', NULL),
('And I''m so pilled up that I rattle.', '"Revolution Rock" - The Clash', NULL),
('I have got the sharpest knife, so I get the biggest slice.', '"Revolution Rock" - The Clash', NULL),
('Blood in the streets in the town of New Haven', '"Peace Frog" - The Doors', 'yale'),
('We need the funk.', '"Give Up the Funk" - Parliament', NULL),
('And the sound that I''m hearing is only the sound of the low spark of high heeled boys.', '"The Low Spark of High Heeled Boys" - Traffic', NULL),
('And the only safe place to live is on an Indian reservation.', '"Ball of Confusion" - The Temptations', NULL),
('Well you know that it''s a shame and a pity you were raised up in the city / And you never learned nothing about country ways', '"Not So Sweet Martha Lorraine" - Country Joe and the Fish', NULL),
('Ich lieb dich nicht; Du liebst mich nicht.', '"Da da da" - Trio', NULL),
('Tap turns on the water, see the waters flow.', '"Tap Turns on the Water" - C.C.S.', NULL),
('Rhonda had a house in Venice, lived on brown rice and cocaine.', '"88 Lines About 44 Women" - The Nails', NULL),
('Everybody''s in despair, every girl and boy.', '"Quinn the Eskimo" - Bob Dylan', NULL),
('Lord Lucan is missing.', '"Lord Lucan is Missing" - The Dodgems', NULL),
('Today Billie Joe McAllister jumped off the Tallahatchee Bridge', '"Ode to Billie Joe" - Bobbie Gentry', NULL),
('The tide is high, but I''m holding on.', '"The Tide is High" - Blondie', NULL),
('And with the way you look I understand you''re not impressed.', '"Alison" - Elvis Costello', NULL),
('But spirit is something that no one destroys.', '"The Low Spark of High Heeled Boys" - Traffic', NULL),
('Don''t talk to me about your big, big heroes', '"Kelly''s Heroes" - Black Grape', NULL),
('Trouble''s gonna come to you', '"Your Time is Gonna Come" - Led Zepplin', NULL),
('I don''t like drinking fancy champy, I''ll stick with Heineken beers.', '"Love Me or Hate Me" - Lady Sovereign', NULL),
('They headed down to old El Paso; thats''s where they ran into a great big hassle.', '"Take the Money and Run" - The Steve Miller Band', 'utep'),
('I''ll write on your tombstone, "I thank you for dinner."', '"Bungle in the Jungle" - Jethro Tull', NULL),
('Taking a bite on a biscuit, the record jumps on a scratch.', '"If I Didn''t Love You" - Squeeze', NULL),
('They were all in love with Diane, they we''re doing it in Texas.', '"Pepper" - Butthole Surfers', 'texas'),
('I got a baby''s brain and an old man''s heart', '"I''m Eighteen" - Alice Cooper', NULL),
('Let fury have the hour / Anger can be power.', '"Clampdown" - The Clash', NULL),
('I like bread and butter. I like toast and jam.', '"Bread and Butter" - The Newbeats', NULL),
('Come on down and meet your maker. Come on down and take a stand.', '"The Stand" - The Alarm', NULL),
('And of all my friends, you''ve been the best to me. / Soon will be the day when I repay you handsomely.', '"Rush" - Big Audio Dynamite', NULL),
('What''s the point of robbery when nothing is worth taking?', '"Stand and Deliver" - Adam and the Ants', NULL),
('If I had my time again / I would do it all the same.', '"Rush" - Big Audio Dynamite', NULL),
('Lights going out, and a kick in the balls.', '"That''s Entertainment" - The Jam', NULL),
('He took it all too far, but boy could he play guitar.', '"Ziggy Stardust" - David Bowie', NULL),
('He is handing the money / He is serving the food / He knows about your party / He is calling you dude.', '"Comfort Eagle" - Cake', NULL),
('With fingernails that shine like justice, and a voice that is dark like tinted glass.', '"Short Skirt Long Jacket" - Cake', NULL),
('You pay for this but they give you that.', '"Hey Hey, My My" - Neil Young', NULL),
('We live on blood / We are Sparta F.C', '"Theme from Sparta FC" - The Fall', NULL),
('You scumbag, you maggot, you cheap lousy faggot', '"Fairytale of New York" - The Pogues', NULL),
('I remember one night the kid cut off his right arm in a bid to save a bit of power.', '"So It Goes" - Nick Lowe', NULL),
('We''re only making plans for Nigel.', '"Making Plans for Nigel" - XTC', NULL),
('But anyone who ever had heart, they wouldn''t turn around and break it.', '"Sweet Jane" - Lou Reed', NULL),
('It''s tough kid, but it''s life.', '"Holiday In Cambodia" - The Dead Kennedys', NULL),
('You''ll work harder with a gun in your back, for a bowl of rice a day.', '"Holiday In Cambodia" - The Dead Kennedys', NULL),
('I''m the all night drug prowling wolf who looks so sick in sun / I''m the white man in the Palais', '"White Man in Hammersmith Palais" - The Clash', NULL),
('Space travel''s in my blood.', '"Another Girl, Another Planet" - The Only Ones', NULL),
('I''m not a coward; I''ve just never been tested.', '"The Impression That I Get" - The Mighty Mighty Bosstones', NULL),
('So let the words of our mouth and the meditation of our heart be acceptable in thy sight, O Fari!', '"By the RIvers of Babylon"-The Melodians', NULL),
('Tetrahydrocannabinol für die Allgemeinheit!', '"Mein Weed" - Nikitaman', NULL),
('I''m just like a turtle crawling out of my shell.', '"Boombastic" - Shaggy', 'maryland'),
('I''m going to Wichita, far from this opera for evermore.', '"Seven Nation Army" - The White Stripes', 'wichita-st'),
('In North Carolina way back in the hills, there lived my pappy and he had him a still.', '"White Lightning" - The Big Bopper', 'unc-asheville'),
('Everybody know I''m a motherfucking monster.', '"Monster" - Kanye West', NULL),
('What ever happened to Leon Trotsky?', '"No More Heroes" - The Stranglers', NULL),
('We''re volunteers of America.', '"Volunteers" - Jefferson Airplane', 'tennessee'),
('Now she''s with one of my good-time buddies, they''re drinking in some crosstown bar.', '"Whipping Post" - The Allman Brothers', NULL),
('Cause now I wanna be your dog.', '"I Wanna Be Your Dog" - Iggy and the Stooges', NULL),
('Well New York City really has it all.', '"Sheena Is a Punk Rocker" - The Ramones', 'columbia'),
('That man could give a fuck about the grin on your face as you walk by randy as a goat.', '"Never Say Never" - Romeo Void', NULL),
('Free Nelson Mandela!', '"Nelson Mandela" - The Specials', NULL),
('Bitch, I''m me!', '"Stand Up" - Ludacris', NULL),
('But where the fuck is the waitress at with my drinks!', '"Stand Up" - Ludacris', NULL),
('You have to let that raga drop.', '"Rock the Casbah" - The Clash', NULL),
('All your compliments and your cutting remarks are captured here in my quotation marks.', '"Everyday I Write the Book" - Elvis Costello', NULL),
('Really don''t mind if you sit this one out.', '"Thick as a Brick" - Jethro Tull', NULL),
('Twenty-one years in captivity / His shoes too small to fit his feet', '"Nelson Mandela" - The Specials', NULL),
('Somehow I stayed thin, while the other guys got fat', '"Rush" - Big Audio Dynamite', NULL),
('Hop in my Chrysler, it''s as big as a whale and it''s about to set sail.', '"Love Shack" - The B-52''s', NULL),
('What have I done?', '"Police On My Back" - The Clash', NULL),
('Look out honey, ''cause I''m using technology', '"Search and Destroy" - Iggy and the Stooges', NULL),
('And then my good friend Shaggy says "Come spend some time, family"', '"44/876" -- Shaggy & Sting', NULL),
('Why you gotta fight wit me at Cheesecake? You know I love to go there.', '"Childs Play" - Drake', NULL),
('I''m a boss, you a worker, bitch.', '"Bodak Yellow" - Cardi B', NULL),
('This will be our year, took a long time to come', '"This Will Be Our Year" - The Zombies', NULL),
('I''m so tired of being lonely, I still have some love to give.', '"Handle With Care" - The Travelling WIlburys', NULL),
('You know he knows just exactly what the facts is.', '"Take the Money and Run" - The Steve Miller Band', NULL),
('That''s where you''ll find me, along with the lovers muggers and thieves - but they''re cool people.', '"Dirty Water" - The Standells', NULL),
('And I''m telling you son, well, it ain''t no fun staring straight down a forty-four.', '"Gimme Three Steps" - Lynyrd Skynyrd', NULL),
('Yeah, we''re just young, dumb and broke but we still got love to give.', '"Young, Dumb And Broke" - Khalid', NULL),
('Spread love- it''s the Brooklyn way.', '"Juicy" - Notorious B.I.G.', 'liu-brooklyn'),
('Gaga googa ga ga googa ga ga goo ga ga', '"Night of the Thumpasaurus People" - Parliament', NULL),
('I want the bomb, I want the P-Funk, I want my funk uncut.', '"P-Funk (Wants to Get Funked Up)" - Parliament', NULL),
('Hallelujah, here she comes.', '"Skateaway" - Dire Straits', NULL),
('I''ve never done bad things.', '"Ashes to Ashes" - David Bowie', NULL),
('The black queen chants the funeral march, the cracked brass bells will ring / To summon back the fire witch to the court of the crimson king', '"The Court of the Crimson King" - King Crimson', 'harvard'),
('Oh workers can you stand it, oh tell me how you can? Will you be a lousy scab or will you be a man?', '"Which Side AreYou On?" - Pete Seeger', 'eastern-ky'),
('Hmm, you''re so pretty, not to talk to you would be a crime.', '"Baby, Baby" - The Vibrators', NULL);